FROM centos:7

RUN yum install -y openssh-server openssh-clients

RUN ssh-keygen -A

COPY ./tz.key.pub /root/.ssh/authorized_keys
COPY ./tz.key /root/.ssh/id_rsa
COPY ./sshd_config /etc/ssh/sshd_config
COPY ./tz.repo /etc/yum.repos.d/tz.repo

CMD ["/usr/sbin/sshd", "-D", "-e"]
