FROM centos:7

LABEL type="Repository-server"

RUN yum install -y epel-release
RUN yum install -y nginx createrepo wget openssh-server openssh-clients supervisor

RUN yum clean all

COPY ./repo/hello-world-1.0.0-1.x86_64.rpm /opt/repo/hello-world-1.0.0-1.x86_64.rpm
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./sshd/sshd_config /etc/ssh/sshd_config
COPY ./supervisord/services.ini /etc/supervisord.d/services.ini

RUN ssh-keygen -A

COPY ./key/tz.key.pub /root/.ssh/authorized_keys
COPY ./key/tz.key /root/.ssh/id_rsa

RUN echo 'root:secret' | chpasswd

CMD [ "supervisord", "-n" ]

EXPOSE 2223 8080